### ISSUE TITLE
Can't attach debugger with node:latest

### ISSUE THREAD

**Issue by VincentLiu028** [PDMLab/vscode-debug-es6-node-docker-sample#1]
I just tried, vscode with this project, seem debugger only get attached with node:4.2.3 as you specified in the docker file. If I change it to node:latest, then debugger can't connect. Is there any reason for this?

**Comment by elias551** [comment]
2 things:
1. Node deprecated the v8 debugger in favor of the chrome debugger:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging

2. Docker seems to block access to localhost binding, you must specify that the debugger should listen from any ip address (ie docker network adapter ip address)

Just change `--debug=5858` with `--inspect=0.0.0.0:5858` in the last line of the Dockerfile, rebuild, et voilà
